name: Release

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
      - name: Build manifests
        run: make release-manifests
      - name: Release manifests
        uses: softprops/action-gh-release@01570a1f39cb168c169c802c3bceb9e93fb10974 # v0.1.15
        with:
          files: |
            _output/components.yaml
            _output/high-availability.yaml
            _output/high-availability-1.21+.yaml
      - name: Build binaries
        run: make build-all
      - name: Release binaries
        uses: softprops/action-gh-release@01570a1f39cb168c169c802c3bceb9e93fb10974 # v0.1.15
        with:
          files: |
            _output/metrics-server-*
